---
# Indexer Manager configuration defaults
indexer_manager_image: "{{ (lookup('url', vault_url + '/v1/kv/data/blithe/config-ansible/roles/indexer-manager/defaults', headers={'X-Vault-Token': vault_token} ) | from_json).data.data.image }}"
indexer_manager_container_name: "{{ (lookup('url', vault_url + '/v1/kv/data/blithe/config-ansible/roles/indexer-manager/defaults', headers={'X-Vault-Token': vault_token} ) | from_json).data.data.container_name }}"
indexer_manager_data_dir: "/data/docker/{{ indexer_manager_container_name }}"
indexer_manager_port: "9696"
