---
- name: Disable ICMP redirects
  sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  notify: restart networking

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  notify: restart networking

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Configure NAT for the virtual network
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: net1
    source: "10.0.0.0/24"
    jump: MASQUERADE
    comment: "NAT for vnet"

- name: Save iptables rules
  shell: netfilter-persistent save
  changed_when: false

- name: Ensure netfilter-persistent service is enabled and started
  service:
    name: netfilter-persistent
    state: started
    enabled: yes
