---
- name: Create Radarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ radarr_data_dir }}"
    - "{{ radarr_movies_dir }}"
    - "{{ radarr_downloads_dir }}"

- name: Set media folder permissions for Radarr
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  loop:
    - "{{ radarr_movies_dir }}"
    - "{{ radarr_downloads_dir }}"

- name: Template Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ radarr_data_dir }}/docker-compose.yml"
    mode: '0644'

- name: Deploy Radarr container
  community.docker.docker_compose_v2:
    project_src: "{{ radarr_data_dir }}"
    state: present
    pull: missing
