FROM wordpress:php8.2-apache

# Install Redis extension
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libzip-dev \
        unzip \
    ; \
    pecl install redis; \
    docker-php-ext-enable redis; \
    # Install OpenTelemetry PHP extension
    pecl install opentelemetry; \
    docker-php-ext-enable opentelemetry; \
    # Cleanup
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

COPY php.ini /usr/local/etc/php/conf.d/99-custom.ini
