---
# defaults file for traefik-internal role

traefik_image: "traefik:v2.10"
traefik_container_name: "traefik"
traefik_config_path: "/etc/traefik"
traefik_log_path: "/var/log/traefik"
traefik_acme_path: "/etc/traefik/acme"
traefik_data_path: "/opt/containers/traefik"
