---
- name: Create Service base config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_base_dir }}/compose/minio"
    - "{{ minio_data_dir }}"

- name: Copy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_base_dir }}{{ item.dest }}"
    mode: '0644'
  loop:
    - { "src": "docker-compose.yml.j2", "dest": "/compose/minio/docker-compose.yml"}

- name: Run Docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_base_dir }}/compose/minio/"
    files:
      - docker-compose.yml
    state: present
    pull: missing
    recreate: always
  become: true

