---
- name: Create Step CA directories
  file:
    path: "{{ step_ca_data_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'

- name: Template Docker Compose file for Step CA
  template:
    src: docker-compose.yml.j2
    dest: "{{ step_ca_data_path }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Deploy Step CA container
  community.docker.docker_compose_v2:
    project_src: "{{ step_ca_data_path }}"
    files:
      - docker-compose.yml
    state: present
  register: step_ca_compose_result

- name: Add ACME provisioner to Step CA
  command: >
    docker exec step-ca step ca provisioner add acme --type ACME
  when: step_ca_compose_result.changed
  retries: 3
  delay: 5
  until: "provisioner_add_result.rc == 0"
  register: provisioner_add_result
  changed_when: provisioner_add_result.rc == 0
