---
# First play: Setup admin user (runs as root)
- name: Initial setup
  hosts: all
  become: yes
  vars:
    ansible_user: "{{ hostvars[inventory_hostname]['ansible_user'] | default('root') }}"
  roles:
    - role: security
      tags: ['security', 'initial_setup']

# Second play: Configure system (runs as admin)
- name: System configuration
  hosts: all
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: docker
      tags: ['docker']

# Third play : Install pangolin and portainer on the machine
- name: Install and configure Pangolin
  hosts: all
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: pangolin
      tags: ['pangolin']


