---
# First play: Setup admin user (runs as root)
- name: Initial setup
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ hostvars[inventory_hostname]['ansible_user'] | default('root') }}"
  roles:
    - role: security
      tags: ['security', 'initial_setup']

# Second play: Configure system (runs as admin)
- name: System configuration
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: docker
      tags: ['docker']

# Third play  Configure Traefik reverse proxy
- name: Configure Traefik
  hosts: "aitbytes.fyi"
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: traefik
      tags: ['traefik']

- name: Install Anki Sync Server
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: anki-sync-server
      tags: ['anki-sync-server']



- name: Install Minio
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: minio
      tags: ['minio']


# Fourth play configure keecloak
# - name: Configure Traefik
#   hosts: aitbytes.fyi
#   become: yes
#   vars:
#     ansible_user: "{{ admin_username }}"
#   roles:
#     - role: keecloak
#       tags: ['keecloak']

# Fifth play install observability stack
- name: Prometheus & Grafana
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: observability
      tags: ['observability']

- name: Install Wordpress
  hosts: debian003
  become: yes
  roles:
    - role: wordpress
      tags: ['wordpress']

- name: Install NSD
  hosts: debian003
  become: yes
  roles:
    - role: nsd
      tags: ['nsd']

- name: Install Copyparty
  hosts: debian003
  become: yes
  roles:
    - role: copyparty
      tags: ['copyparty']

- name: Install Browserless
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: browserless
      tags: ['browserless']

- name: Install SeaweedFS
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: seaweedfs
      tags: ['seaweedfs']

- name: Install Vault
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: vault
      tags: ['vault']


- name: Install Adminer
  hosts: debian003
  become: yes
  roles:
    - role: adminer
      tags: ['adminer']

- name: Install Watchtower
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: watchtower
      tags: ['watchtower']


# Fourth play  Configure additional services
#- name: Configure additional services
#  hosts: all
#  become: yes
#  vars:
#    ansible_user: "{{ admin_username }}"
#  roles:
#    - role: services
#      tags: ['services']

