---
# First play: Setup admin user (runs as root)
- name: Initial setup
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ hostvars[inventory_hostname]['ansible_user'] | default('root') }}"
  roles:
    - role: security
      tags: ['security', 'initial_setup']

# Second play: Configure system (runs as admin)
- name: System configuration
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: docker
      tags: ['docker']

# Third play  Configure Traefik reverse proxy
- name: Configure Traefik
  hosts: "aitbytes.fyi"
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: traefik
      tags: ['traefik']

# Fourth play configure keecloak
- name: Configure Traefik
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: keecloak
      tags: ['keecloak']

# Fifth play install observability stack
- name: Prometheus & Grafana
  hosts: aitbytes.fyi
  become: yes
  vars:
    ansible_user: "{{ admin_username }}"
  roles:
    - role: observability
      tags: ['observability']

- name: Install Wordpress
  hosts: debian003
  become: yes
  roles:
    - role: wordpress
      tags: ['wordpress']


# Fourth play  Configure additional services
#- name: Configure additional services
#  hosts: all
#  become: yes
#  vars:
#    ansible_user: "{{ admin_username }}"
#  roles:
#    - role: services
#      tags: ['services']

